version: "3.8"
services:
  email-service:
    container_name: email-service
    image: email-service
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8093:8080"
    networks:
        - wavshare-nw

networks:
  wavshare-nw:
    name: wavshare-nw
    external: true