version: "3.8"
services:
  email-service:
    container_name: email-service
    depends_on:
      - email-db
    image: email-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8087:8087"
  email-db:
    container_name: email-db
    restart: always
    image: redis:7.0.5-alpine
    ports:
      - "6382:6382"
    expose:
      - 6382
    volumes:
      - email-db-volume:/var/lib/email-db

volumes:
  email-db-volume: